//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerageApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public Nullable<int> Contract { get; set; }
        public Nullable<int> Broker { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Broker Broker1 { get; set; }
        public virtual Contract Contract1 { get; set; }
    }
}
