//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerageApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DismissedBrokers
    {
        public int Id { get; set; }
        public Nullable<int> Broker { get; set; }
        public Nullable<System.DateTime> DateDismiss { get; set; }
    
        public virtual Broker Broker1 { get; set; }
    }
}
